### ISSUE TITLE
Forecasts should take in 4 parameters: start date, end date, forecast horizon, and seasonality

### ISSUE THREAD

**Issue by davidjhodge** [tmoon8730/flow-predictionplayground#4]
* Forecasts should take four parameters into account
    * Start date
    * End date
    * Forecast Horizon (1d/1w/1m/3m/6m/1y)
    * Seasonality (1 - 10?)

**Comment by tmoon8730** [comment]
Using Prophet i'm just outputting daily, monthly, and yearly forecast data so we don't have to take the parameters into account. I'm also outputing all known data and 10 series worth of forecasted data. The front end can parse out the needed data from the user parameters.
