### ISSUE TITLE
Create endpoint that returns a sales time series for each variant (including forecasted time series)

### ISSUE THREAD

**Issue by davidjhodge** [tmoon8730/flow-predictionplayground#5]
* Create endpoint that returns a sales time series for each variant (including forecasted time series)
    * The end goal is to display a graph of the past and future sales for each variant
        * x-axis: Date
        * y-axis: Number of sales

**Comment by tmoon8730** [comment]
Endpoint is in as /forecast/triggerForecast/:variant_id

The id is currently the source id from Shopify so that'll have to change at a later time to the Postgres ID.
